<?php

namespace Fail\StatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    public function getRank(Player $p)
    {
        $result = $this->createQueryBuilder('p')
            ->select('COUNT(p)')
            ->where('p.elo > '.$p->getElo())
            ->getQuery()
            ->getSingleScalarResult();
        return $result + 1;
    }
    
    public function getEx(Player $p)
    {
        $result = $this->createQueryBuilder('p')
            ->select('COUNT(p)')
            ->where('p.elo = '.$p->getElo())
            ->getQuery()
            ->getSingleScalarResult();
        
        return $result > 1;
    }
}