player:
    resource: "@FailStatBundle/Resources/config/routing/player.yml"
    prefix: /player

encounter:
    resource: "@FailStatBundle/Resources/config/routing/encounter.yml"
    prefix: /encounter

event:
    resource: "@FailStatBundle/Resources/config/routing/encounter.yml"
    prefix: /event

FailStatBundle_homepage:
    pattern:  /
    defaults: { _controller: FailStatBundle:Default:index }
