admin_access:
    resource: "@FailStatBundle/Resources/config/admin.yml"
    prefix: /admin

homepage:
    pattern:  /
    defaults: { _controller: FailStatBundle:Default:index }

report:
    pattern: /report
    defaults:
        _controller: FailStatBundle:Default:report
