parameters:
#    fail_stat.example.class: Fail\StatBundle\Example

services:
#    fail_stat.example:
#        class: %fail_stat.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
